
public class StudentAllocModel 
{
    // public int AllocationID { get; set; }
    // Don't need AllocationID because generated by table 
    public Decimal Amount { get; set; }
    public int AllocationYear { get; set; }
    public int StudentID {get; set;}
    
}